M48
; DRILL file {KiCad 8.0.9} date 2025-05-10T12:34:38+0100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-05-10T12:34:38+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.9
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.800
%
G90
G05
T1
X118.575Y-108.97
X123.425Y-108.97
T2
X118.275Y-112.0
X123.725Y-112.0
M30
