#ifndef _A2BUS_H
#define _A2BUS_H

#ifdef PICO_RP2040
#include "a2bus_rp2040.pio.h"	//Generated by pio assembler
#else
#include "a2bus_rp2350.pio.h"	//Generated by pio assembler
#endif

#ifdef PICO_RP2040
#define SM_LISTENER 0
#else
#define SM_LISTENER 0
#define SM_A2BUS    1
#endif


void InitPIO();

static inline uint32_t GetAppleBusBlocking() {
  return pio_sm_get_blocking(pio0, SM_LISTENER);
}

//Update MegaFlash Registers
//Input: chunk - Which chunk of registers 
//               0 for $C0C0-$C0C3, 1 for $C0C4-$C0C7 and so on
//       value - MegaFlash Registers value
static inline void UpdateMegaFlashRegisters(const uint32_t chunk,const uint32_t value) {
#ifdef PICO_RP2040
  pio_sm_put(pio0, chunk, value);
#else 
  pio0->rxf_putget[SM_A2BUS][chunk]= value;
#endif
}

#endif
