#include <stdint.h>
#include <assert.h>
#include "flash.h"
#include "encryption.h"

/***************************************************************
Wifi Passphrase is sensitive information. But the source code
of this project is open. So, it is meaningless to implement
a strong, complicated encryption algorithm for the passphrase.
Having said that, it seems to be a bad idea to store the passphrase
in plain text without any encryption.

So, a simple XOR encryption algorithm is used. A series of pseudo 
random number is generated by xorshift alogirthm to encrypt/decrypt
data.
****************************************************************/



static uint64_t GetEncryptionKey() {
  static uint64_t key = 0;
  static bool keyGenerated = false;
  
  if (!keyGenerated) {
    const uint64_t value64 = 0xa384964b31bed649ull; //an arbitrary value
    const uint64_t uniqueid  = tsReadUniqueIDDevice0();
    
    key = uniqueid ^ value64;
    if (key==0) key = value64; //key cannot be zero.
    keyGenerated = true;
  }
  
  return key;
}

static uint64_t state = 1;  //cannot be zero
static uint64_t xorshift64() {
  /* Algorithm "xor" from p. 4 of Marsaglia, "Xorshift RNGs" */  
	uint64_t x = state;
	x ^= x << 13;
	x ^= x >> 7;
	x ^= x << 17;
	return state = x;
}

void Decrypt(uint8_t* destBuffer,const uint8_t* srcBuffer, uint32_t len) {
  assert(len%8==0);
  assert((uint32_t)destBuffer%4==0);
  assert((uint32_t)srcBuffer %4==0);  
  
  //reset the seed which is the encryption key
  state = GetEncryptionKey();
  
  uint32_t* src = (uint32_t*)srcBuffer;
  uint32_t* dest= (uint32_t*)destBuffer;
  
  while (len!=0) {
    uint64_t randnum = xorshift64();
    
    *dest++ = *src++ ^ ((uint32_t)randnum);
    *dest++ = *src++ ^ ((uint32_t)(randnum>>32));
    len -=8;
  }
}





