M48
; DRILL file {KiCad 9.0.3} date 2025-07-22T08:59:43+0100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-07-22T08:59:43+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.3
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C2.700
%
G90
G05
T1
X138.275Y-108.97
X143.125Y-108.97
T2
X137.975Y-112.0
X143.425Y-112.0
T3
X162.4Y-82.233
M30
