M48
; DRILL file {KiCad 9.0.4} date 2025-09-07T09:46:20+0100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-09-07T09:46:20+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.800
%
G90
G05
T1
X118.575Y-91.97
X123.425Y-91.97
T2
X118.275Y-95.0
X123.725Y-95.0
M30
