/* Generated by CMake from build_id.h.in — do not edit. */
#ifndef FIRMWARE_BUILD_ID_H
#define FIRMWARE_BUILD_ID_H

#define FIRMWARE_BUILD_TIMESTAMP (0u)
#define FIRMWARE_BUILD_TIMESTAMP_STR "unknown"

#endif
